name: animated_book_widget
description: A Flutter package providing an interactive method to display content, resembling the experience of flipping through pages.
version: 1.0.1
homepage: https://www.d-velopers.com
repository: https://github.com/the-d-velopers/animated_book_widget/

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0