name: Publish to pub.dev

on:
  push:
    branches:
      - release

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish package
        uses: k-paxian/dart-package-publisher@master
        with:
          #accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          #refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          credentialJson: ${{secrets.CREDENTIAL_JSON}}
          skipTests: true
          suppressBuildRunner: true